### ISSUE TITLE
tkinter not found :(

### ISSUE THREAD

**Issue by davad00** [bjia56/portable-python#81]
Traceback (most recent call last):
  File "C:\Users\shuhs\AppData\Local\CarManagmentAssistant\BranchClient.py", line 3, in <module>
    from tkinter import scrolledtext
  File "C:\Users\shuhs\AppData\Local\CarManagmentAssistant\python\Lib\tkinter\__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'

**Comment by bjia56** [comment]
Windows releases are currently missing the dependencies to build tkinter. I'll look into adding them

**Comment by bjia56** [comment]
Latest Windows `full` builds now have tkinter included.
